# Spring boot application
spring:
  datasource:
      driver-class-name:  com.mysql.jdbc.Driver
      druid:
        filters: wall,stat,slf4j
        poolPreparedStatements: true
        stat-view-servlet:
          login-username: hello
          login-password: hello
  profiles:
    active: development
server:
  port: 7000
  session:
    timeout: 1800
mybatis:
  mapper-locations: classpath:/com/upms/rpc/service/dao/mapper/*Mapper.xml
pagehelper:
  support-methods-arguments: true
  params: pageNum=page
# Base packages to scan Dubbo Components (e.g., @Service, @Reference)
dubbo:
  scan:
    basePackages: com.upms.rpc.service.impl
  application:
    id: upms-rpc-service
    name: upms-rpc-service
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
  registry:
    id: upms-registry
    address: zookeeper://zkserver:2181
--- # 开发配置
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/aaron?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: password
  resources:
    chain:
      gzipped: true