spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aaron?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: password
  resources:
    chain:
      gzipped: true
server:
  port: 7000
  session:
    timeout: 1800
dubbo:
  application:
    id: upms-server
    name: upms-server
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: upms-registry
    address: zookeeper://zkserver:2181